
target_panel: {
  motors_pos_cur: {
    'motors_pos_cur_0': 'motors_pos_cur_arm_l_01',
    'motors_pos_cur_1': 'motors_pos_cur_arm_l_02',
    'motors_pos_cur_2': 'motors_pos_cur_arm_l_03',
    'motors_pos_cur_3': 'motors_pos_cur_arm_l_04',
    'motors_pos_cur_4': 'motors_pos_cur_arm_l_05',
    'motors_pos_cur_5': 'motors_pos_cur_arm_l_06',
    'motors_pos_cur_6': 'motors_pos_cur_arm_l_07',
    'motors_pos_cur_7': 'motors_pos_cur_arm_r_01',
    'motors_pos_cur_8': 'motors_pos_cur_arm_r_02',
    'motors_pos_cur_9': 'motors_pos_cur_arm_r_03',
    'motors_pos_cur_10': 'motors_pos_cur_arm_r_04',
    'motors_pos_cur_11': 'motors_pos_cur_arm_r_05',
    'motors_pos_cur_12': 'motors_pos_cur_arm_r_06',
    'motors_pos_cur_13': 'motors_pos_cur_arm_r_07',
    'motors_pos_cur_14': 'motors_pos_cur_head_yaw',
    'motors_pos_cur_15': 'motors_pos_cur_head_pitch',
    'motors_pos_cur_16': 'motors_pos_cur_waist_pitch',
    'motors_pos_cur_17': 'motors_pos_cur_waist_roll',
    'motors_pos_cur_18': 'motors_pos_cur_waist_yaw',
    'motors_pos_cur_19': 'motors_pos_cur_hip_l_roll',
    'motors_pos_cur_20': 'motors_pos_cur_hip_l_yaw',
    'motors_pos_cur_21': 'motors_pos_cur_hip_l_pitch',
    'motors_pos_cur_22': 'motors_pos_cur_knee_l_pitch',
    'motors_pos_cur_23': 'motors_pos_cur_ankle_l_pitch',
    'motors_pos_cur_24': 'motors_pos_cur_ankle_l_roll',
    'motors_pos_cur_25': 'motors_pos_cur_hip_r_roll',
    'motors_pos_cur_26': 'motors_pos_cur_hip_r_yaw',
    'motors_pos_cur_27': 'motors_pos_cur_hip_r_pitch',
    'motors_pos_cur_28': 'motors_pos_cur_knee_r_pitch',
    'motors_pos_cur_29': 'motors_pos_cur_ankle_r_pitch',
    'motors_pos_cur_30': 'motors_pos_cur_ankle_r_roll'
  },
  motors_vel_cur: {
    'motors_vel_cur_0': 'motors_vel_cur_arm_l_01',
    'motors_vel_cur_1': 'motors_vel_cur_arm_l_02',
    'motors_vel_cur_2': 'motors_vel_cur_arm_l_03',
    'motors_vel_cur_3': 'motors_vel_cur_arm_l_04',
    'motors_vel_cur_4': 'motors_vel_cur_arm_l_05',
    'motors_vel_cur_5': 'motors_vel_cur_arm_l_06',
    'motors_vel_cur_6': 'motors_vel_cur_arm_l_07',
    'motors_vel_cur_7': 'motors_vel_cur_arm_r_01',
    'motors_vel_cur_8': 'motors_vel_cur_arm_r_02',
    'motors_vel_cur_9': 'motors_vel_cur_arm_r_03',
    'motors_vel_cur_10': 'motors_vel_cur_arm_r_04',
    'motors_vel_cur_11': 'motors_vel_cur_arm_r_05',
    'motors_vel_cur_12': 'motors_vel_cur_arm_r_06',
    'motors_vel_cur_13': 'motors_vel_cur_arm_r_07',
    'motors_vel_cur_14': 'motors_vel_cur_head_yaw',
    'motors_vel_cur_15': 'motors_vel_cur_head_pitch',
    'motors_vel_cur_16': 'motors_vel_cur_waist_pitch',
    'motors_vel_cur_17': 'motors_vel_cur_waist_roll',
    'motors_vel_cur_18': 'motors_vel_cur_waist_yaw',
    'motors_vel_cur_19': 'motors_vel_cur_hip_l_roll',
    'motors_vel_cur_20': 'motors_vel_cur_hip_l_yaw',
    'motors_vel_cur_21': 'motors_vel_cur_hip_l_pitch',
    'motors_vel_cur_22': 'motors_vel_cur_knee_l_pitch',
    'motors_vel_cur_23': 'motors_vel_cur_ankle_l_pitch',
    'motors_vel_cur_24': 'motors_vel_cur_ankle_l_roll',
    'motors_vel_cur_25': 'motors_vel_cur_hip_r_roll',
    'motors_vel_cur_26': 'motors_vel_cur_hip_r_yaw',
    'motors_vel_cur_27': 'motors_vel_cur_hip_r_pitch',
    'motors_vel_cur_28': 'motors_vel_cur_knee_r_pitch',
    'motors_vel_cur_29': 'motors_vel_cur_ankle_r_pitch',
    'motors_vel_cur_30': 'motors_vel_cur_ankle_r_roll'
  },
  rpy: {
    'rpy_0': 'rpy_x',
    'rpy_1': 'rpy_y',
    'rpy_2': 'rpy_z',
  },
  fL: {
    'fL_0': 'fL_x',
    'fL_1': 'fL_y',
    'fL_2': 'fL_z',
  },
  fR: {
    'fR_0': 'fR_x',
    'fR_1': 'fR_y',
    'fR_2': 'fR_z',
  },
  basePos: {
    'basePos_0': 'basePos_x',
    'basePos_1': 'basePos_y',
    'basePos_2': 'basePos_z',
  },
  baseLinVel: {
    'baseLinVel_0': 'baseLinVel_x',
    'baseLinVel_1': 'baseLinVel_y',
    'baseLinVel_2': 'baseLinVel_z',
  },
  baseAcc: {
    'baseAcc_0': 'baseAcc_x',
    'baseAcc_1': 'baseAcc_y',
    'baseAcc_2': 'baseAcc_z',
  },
  baseAngVel: {
    'baseAngVel_0': 'baseAngVel_x',
    'baseAngVel_1': 'baseAngVel_y',
    'baseAngVel_2': 'baseAngVel_z',
  },
}
